export const INSURERS = [
  "Star Health", "HDFC ERGO", "Care Health", "Niva Bupa", "ICICI Lombard", 
  "Bajaj Allianz", "Ayushman Bharat (PM-JAY)", "CGHS", "EHS", "Aditya Birla Health"
];

export const MOCK_LABS = [
  // Aligarh Labs
  {
    id: 1,
    name: "Dr. Lal PathLabs - Ramghat Road",
    city: "Aligarh",
    address: "Ramghat Road, Near Niranjan Puri, Aligarh",
    rating: 4.8,
    reviewCount: 420,
    homeCollection: true,
    nablAccredited: true,
    popularTests: ["Swasthfit Full Body Checkup (₹1,299)", "Thyroid Profile (₹450)", "HbA1c Diabetes Test (₹500)"],
    avgTurnaround: "6 Hours",
    phone: "+91 571 2742222"
  },
  {
    id: 2,
    name: "Metropolis Healthcare & Pathology",
    city: "Aligarh",
    address: "Centre Point, Samad Road, Aligarh",
    rating: 4.7,
    reviewCount: 310,
    homeCollection: true,
    nablAccredited: true,
    popularTests: ["Lipid Profile (₹650)", "CBC Blood Test (₹350)", "Vitamin D & B12 Combo (₹1,400)"],
    avgTurnaround: "8 Hours",
    phone: "+91 571 2743333"
  },
  {
    id: 3,
    name: "JNMC AMU Advanced Pathology Wing",
    city: "Aligarh",
    address: "AMU Medical Campus, Aligarh",
    rating: 4.9,
    reviewCount: 950,
    homeCollection: false,
    nablAccredited: true,
    popularTests: ["Brain MRI Scan (₹2,200)", "Full Body CT Scan (₹1,150)", "Biopsy & Histopathology (₹800)"],
    avgTurnaround: "12 Hours",
    phone: "+91 571 2720036"
  },

  // Agra Labs
  {
    id: 4,
    name: "Agilus Diagnostics (SRL)",
    city: "Agra",
    address: "Sanjay Place, Commercial Complex, Agra",
    rating: 4.8,
    reviewCount: 540,
    homeCollection: true,
    nablAccredited: true,
    popularTests: ["Active Health Package (₹1,599)", "Liver Function Test (LFT) (₹550)", "KFT Renal Panel (₹600)"],
    avgTurnaround: "6 Hours",
    phone: "+91 562 2851111"
  },
  {
    id: 5,
    name: "Dr. Lal PathLabs - Civil Lines",
    city: "Agra",
    address: "Near Delhi Gate, Civil Lines, Agra",
    rating: 4.7,
    reviewCount: 480,
    homeCollection: true,
    nablAccredited: true,
    popularTests: ["Dengue & Malaria Panel (₹850)", "Thyroid & Lipid Combo (₹950)"],
    avgTurnaround: "6 Hours",
    phone: "+91 562 2852222"
  },

  // Mathura Labs
  {
    id: 6,
    name: "Dr. Lal PathLabs - Dampier Nagar",
    city: "Mathura",
    address: "Dampier Nagar, Near Junction Road, Mathura",
    rating: 4.7,
    reviewCount: 360,
    homeCollection: true,
    nablAccredited: true,
    popularTests: ["Swasthfit Total Checkup (₹1,399)", "Blood Sugar Fasting (₹120)"],
    avgTurnaround: "8 Hours",
    phone: "+91 565 2405555"
  },
  {
    id: 7,
    name: "KD Hospital Pathology & Imaging Wing",
    city: "Mathura",
    address: "NH-2 Delhi-Mathura Highway, Mathura",
    rating: 4.8,
    reviewCount: 610,
    homeCollection: false,
    nablAccredited: true,
    popularTests: ["1.5T MRI Brain/Spine (₹4,200)", "High Speed CT Scan (₹2,400)"],
    avgTurnaround: "4 Hours",
    phone: "+91 565 2825000"
  },

  // New Delhi Labs
  {
    id: 8,
    name: "Mahajan Imaging & Diagnostic Centre",
    city: "New Delhi",
    address: "Hauz Khas Enclave, New Delhi",
    rating: 4.9,
    reviewCount: 1420,
    homeCollection: true,
    nablAccredited: true,
    popularTests: ["3T Cardiac MRI (₹9,500)", "PET CT Scan (₹18,000)", "Whole Body Scan (₹12,000)"],
    avgTurnaround: "3 Hours",
    phone: "+91 11 4343 4343"
  },
  {
    id: 9,
    name: "Max Lab Saket",
    city: "New Delhi",
    tier: "Metro",
    address: "Press Enclave Marg, Saket, New Delhi",
    rating: 4.8,
    reviewCount: 1150,
    homeCollection: true,
    nablAccredited: true,
    popularTests: ["Executive Health Audit (₹2,999)", "Comprehensive Cancer Markers (₹4,500)"],
    avgTurnaround: "5 Hours",
    phone: "+91 11 2651 5050"
  }
];

export const PROCEDURE_CALCULATOR_DATA = [
  {
    procedure: "Coronary Angioplasty (Stent)",
    category: "Cardiology",
    govtEst: 45000,
    privateAvg: 185000,
    privateLuxury: 260000,
    recoveryDays: "2-3 Days",
    insuranceCovered: true
  },
  {
    procedure: "Total Knee Replacement (Single)",
    category: "Orthopedics",
    govtEst: 65000,
    privateAvg: 210000,
    privateLuxury: 320000,
    recoveryDays: "4-5 Days",
    insuranceCovered: true
  }
];

export const MOCK_HOSPITALS = [
  // ---------------- ALIGARH ----------------
  {
    id: 206,
    name: "Tyagi Hospital & Maternity Centre",
    city: "Aligarh",
    tier: "Regional City",
    state: "Uttar Pradesh",
    address: "Ramghat Road, Near Niranjan Puri, Aligarh",
    latitude: 27.8990,
    longitude: 78.0920,
    type: "Private",
    rating: 4.7,
    reviewCount: 480,
    isNabhAccredited: true,
    isJciAccredited: false,
    is24x7: true,
    hasEmergency: true,
    hasIcu: true,
    hasBloodBank: true,
    hasParking: true,
    hasWheelchairAccess: true,
    availableBeds: 25,
    availableVentilators: 6,
    emergencyContact: "+91 571 2740050",
    coverImageUrl: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=800",
    consultationFee: 500,
    mriCost: 4500,
    ctScanCost: 2600,
    icuPerDayCost: 7500,
    waitingTimeMinutes: 10,
    distanceKm: 2.2,
    specialties: ["Gynecology", "Pediatrics", "General Surgery", "Orthopedics", "Maternity"],
    acceptedInsurances: ["Star Health", "Care Health", "Ayushman Bharat (PM-JAY)", "Niva Bupa"],
    patientSatisfactionPct: 95
  },
  {
    id: 207,
    name: "Gandhi Eye Hospital",
    city: "Aligarh",
    tier: "Regional City",
    state: "Uttar Pradesh",
    address: "Ramghat Road, Opposite AMU Campus, Aligarh",
    latitude: 27.9010,
    longitude: 78.0880,
    type: "Government",
    rating: 4.8,
    reviewCount: 1850,
    isNabhAccredited: true,
    isJciAccredited: false,
    is24x7: true,
    hasEmergency: true,
    hasIcu: false,
    hasBloodBank: true,
    hasParking: true,
    hasWheelchairAccess: true,
    availableBeds: 60,
    availableVentilators: 4,
    emergencyContact: "+91 571 2700021",
    coverImageUrl: "https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?auto=format&fit=crop&q=80&w=800",
    consultationFee: 150,
    mriCost: 3800,
    ctScanCost: 2000,
    icuPerDayCost: 3500,
    waitingTimeMinutes: 20,
    distanceKm: 1.8,
    specialties: ["Ophthalmology", "Cataract Surgery", "Retina & Cornea Care", "Glaucoma"],
    acceptedInsurances: ["Ayushman Bharat (PM-JAY)", "CGHS", "Star Health"],
    patientSatisfactionPct: 96
  },
  {
    id: 208,
    name: "Malkhan Singh District Hospital",
    city: "Aligarh",
    tier: "Regional City",
    state: "Uttar Pradesh",
    address: "Near Aligarh Junction Railway Station, Aligarh",
    latitude: 27.8850,
    longitude: 78.0750,
    type: "Government",
    rating: 4.4,
    reviewCount: 1420,
    isNabhAccredited: false,
    isJciAccredited: false,
    is24x7: true,
    hasEmergency: true,
    hasIcu: true,
    hasBloodBank: true,
    hasParking: true,
    hasWheelchairAccess: true,
    availableBeds: 80,
    availableVentilators: 8,
    emergencyContact: "+91 571 2400123",
    coverImageUrl: "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&q=80&w=800",
    consultationFee: 50,
    mriCost: 1800,
    ctScanCost: 1000,
    icuPerDayCost: 2000,
    waitingTimeMinutes: 30,
    distanceKm: 1.5,
    specialties: ["General Medicine", "Emergency Care", "Pediatrics", "Orthopedics"],
    acceptedInsurances: ["Ayushman Bharat (PM-JAY)", "CGHS"],
    patientSatisfactionPct: 87
  },
  {
    id: 201,
    name: "Jawaharlal Nehru Medical College (JNMC – AMU)",
    city: "Aligarh",
    tier: "Regional City",
    state: "Uttar Pradesh",
    address: "Aligarh Muslim University Campus, Medical Road, Aligarh",
    latitude: 27.9152,
    longitude: 78.0776,
    type: "Government",
    rating: 4.8,
    reviewCount: 2100,
    isNabhAccredited: true,
    isJciAccredited: false,
    is24x7: true,
    hasEmergency: true,
    hasIcu: true,
    hasBloodBank: true,
    hasParking: true,
    hasWheelchairAccess: true,
    availableBeds: 110,
    availableVentilators: 22,
    emergencyContact: "+91 571 2720036",
    coverImageUrl: "https://images.unsplash.com/photo-1538108149393-fbbd81895907?auto=format&fit=crop&q=80&w=800",
    consultationFee: 100,
    mriCost: 2200,
    ctScanCost: 1150,
    icuPerDayCost: 2800,
    waitingTimeMinutes: 30,
    distanceKm: 2.1,
    specialties: ["Cardiology", "Pediatrics", "Neurosciences", "Oncology", "Radiology"],
    acceptedInsurances: ["Ayushman Bharat (PM-JAY)", "CGHS", "EHS"],
    patientSatisfactionPct: 94
  },

  // ---------------- AGRA ----------------
  {
    id: 101,
    name: "Pushpanjali Hospital & Research Centre",
    city: "Agra",
    tier: "Regional City",
    state: "Uttar Pradesh",
    address: "Delhi Gate, Civil Lines, Agra",
    latitude: 27.1983,
    longitude: 78.0061,
    type: "Private",
    rating: 4.7,
    reviewCount: 740,
    isNabhAccredited: true,
    isJciAccredited: false,
    is24x7: true,
    hasEmergency: true,
    hasIcu: true,
    hasBloodBank: true,
    hasParking: true,
    hasWheelchairAccess: true,
    availableBeds: 32,
    availableVentilators: 10,
    emergencyContact: "+91 562 2854040",
    coverImageUrl: "https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?auto=format&fit=crop&q=80&w=800",
    consultationFee: 700,
    mriCost: 5500,
    ctScanCost: 3100,
    icuPerDayCost: 9000,
    waitingTimeMinutes: 15,
    distanceKm: 2.5,
    specialties: ["Cardiology", "Neurology", "Gastroenterology", "Oncology", "Orthopedics"],
    acceptedInsurances: ["Star Health", "Care Health", "Ayushman Bharat (PM-JAY)", "HDFC ERGO"],
    patientSatisfactionPct: 94
  },

  // ---------------- MATHURA ----------------
  {
    id: 301,
    name: "KD Medical College Hospital & Research Center",
    city: "Mathura",
    tier: "Regional City",
    state: "Uttar Pradesh",
    address: "24 Km Stone, NH-2, Delhi-Mathura Road, Akbarpur, Mathura",
    latitude: 27.5706,
    longitude: 77.6322,
    type: "Private",
    rating: 4.8,
    reviewCount: 680,
    isNabhAccredited: true,
    isJciAccredited: false,
    is24x7: true,
    hasEmergency: true,
    hasIcu: true,
    hasBloodBank: true,
    hasParking: true,
    hasWheelchairAccess: true,
    availableBeds: 45,
    availableVentilators: 12,
    emergencyContact: "+91 565 2825000",
    coverImageUrl: "https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?auto=format&fit=crop&q=80&w=800",
    consultationFee: 500,
    mriCost: 4200,
    ctScanCost: 2400,
    icuPerDayCost: 7000,
    waitingTimeMinutes: 15,
    distanceKm: 5.4,
    specialties: ["Cardiology", "Orthopedics", "Nephrology", "Pediatrics", "Gynecology"],
    acceptedInsurances: ["Star Health", "Ayushman Bharat (PM-JAY)", "Care Health", "Niva Bupa"],
    patientSatisfactionPct: 95
  }
];

export const MOCK_DOCTORS = [
  {
    id: 101,
    hospitalId: 206,
    name: "Dr. R. K. Tyagi",
    qualification: "MD, MS (Obstetrics & Gynecology)",
    specialization: "Gynecology",
    experienceYears: 26,
    consultationFee: 500,
    rating: 4.9,
    languages: "English, Hindi",
    avatarUrl: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=300",
    availableSlots: ["10:00 AM", "01:00 PM", "04:30 PM"]
  }
];
